title: Budding Coders or Coding Buddies (one of the two)
author: Cheri Haggard
email: cheri@MATHmaniaRobotics.com
description: > # this means to ignore newlines until "baseurl:"
  Coding for kids (of all ages) but our classes feature kids from 8-18.  We use free internet resources that kids around the world can access: Khan Academy, code.org, and scratch.mit.edu

# social links
twitter_username: your-twitter-handle
github_username:  gonzocher
facebook_username: mathmaniarobotics

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
